[package]
name = "laim"
authors = ["Connor Mahaffey"]
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false
build = "build.rs"

[dependencies]
slint = "1.0.2"

[build-dependencies]
slint-build = "1.0.2"

