import { TabWidget, VerticalBox, TextEdit } from "std-widgets.slint";
import { ControlPage, ControlPageHandler } from "control_page.slint";
import { SettingsPage, SettingsPageHandler } from "settings_page.slint";
export { ControlPageHandler, SettingsPageHandler }

export component App inherits Window {
    out property <string> download_instance_url: download_page.instance_url;
    out property <string> download_username_input: download_page.username_input;
    out property <string> download_password_input: download_page.password_input;
    out property <string> download_two_factor_input: download_page.two_factor_input;
    in property <string> download_log_output <=> download_page.log_output;
    in property <bool> download_ui_enabled <=> download_page.ui_enabled;

    out property <string> upload_instance_url: upload_page.instance_url;
    out property <string> upload_username_input: upload_page.username_input;
    out property <string> upload_password_input: upload_page.password_input;
    out property <string> upload_two_factor_input: upload_page.two_factor_input;
    in property <string> upload_log_output <=> upload_page.log_output;
    in property <bool> upload_ui_enabled <=> upload_page.ui_enabled;

    in property <bool> upload_profile_settings <=> settings_page.upload_profile_settings;
    in property <bool> upload_community_subs <=> settings_page.upload_community_subs;
    in property <bool> upload_community_blocks <=> settings_page.upload_community_blocks;
    in property <bool> upload_user_blocks <=> settings_page.upload_user_blocks;
    in property <bool> upload_user_saved_posts <=> settings_page.upload_user_saved_posts;
    in property <bool> sync_removals <=> settings_page.sync_removals;
    in property <bool> confirm_uploads  <=> settings_page.confirm_uploads;
    in property <bool> write_api_profiles <=> settings_page.write_api_profiles;

    title: "LASIM";
    min-width: 280px;
    min-height: 440px;
    preferred-width: 280px;
    preferred-height: 440px;

    VerticalBox {
        alignment: start;
        TabWidget {
            Tab {
                title: "Download";
                download_page := ControlPage {
                    type: "Download";
                }
            }
            Tab {
                title: "Upload";
                upload_page := ControlPage {
                    type: "Upload";
                }
            }
            Tab {
                title: "Settings";
                settings_page := SettingsPage {}
            }
            Tab {
                title: "About";

                VerticalBox {
                    width: 250px;
                    alignment: start;

                    Text {
                        font-size: 20px;
                        font-weight: 900;
                        text: "LASIM 0.2.2";
                    }
                    Text {
                        text: "Lemmy BE API Version 0.18.3";
                    }
                    Text {
                        text: "Created by Connor Mahaffey";
                    }
                    Text {
                        text: "https://github.com/CMahaff/lasim";
                    }
                    Text {
                        text: "Additional Contributors";
                        font-size: 14px;
                        min-height: 40px;
                        vertical-alignment: bottom;
                    }
                    Text {
                        text: "@aidandenlinger";
                    }
                    Text {
                        text: "Andy Kittner";
                    }
                }
            }
        }
    }
}
