import { Button, VerticalBox, HorizontalBox,
 TabWidget, LineEdit, ScrollView, TextEdit } from "std-widgets.slint";

export global ControlPageHandler {
    callback clicked(string);
}

export component ControlPage inherits VerticalBox {
    in-out property <string> type;
    out property <string> instance_url: instance_url_object.text;
    out property <string> username_input: username_input_object.text;
    out property <string> password_input: password_input_object.text;
    out property <string> two_factor_input: two_factor_input_object.text;
    in property <string> log_output;
    in property <bool> ui_enabled: true;

    alignment: stretch;

    instance_url_object := LineEdit {
        vertical-stretch: 0;
        placeholder-text: "Instance URL";
        min-width: 250px;
        enabled: ui_enabled;
    }
    username_input_object := LineEdit {
        vertical-stretch: 0;
        placeholder-text: "Username/Email";
        min-width: 250px;
        enabled: ui_enabled;
    }
    password_input_object := LineEdit {
        vertical-stretch: 0;
        placeholder-text: "Password";
        input-type: password;
        min-width: 250px;
        enabled: ui_enabled;
    }
    two_factor_input_object := LineEdit {
        vertical-stretch: 0;
        placeholder-text: "2FA Token (if enabled)";
        min-width: 250px;
        enabled: ui_enabled;
    }

    HorizontalLayout {
        vertical-stretch: 1;
        alignment: stretch;
        VerticalLayout {
            min-width: 250px;
            alignment: stretch;
            HorizontalBox {
                alignment: center;
                vertical-stretch: 0;
                Button {
                    text: type;
                    width: 120px;
                    enabled: ui_enabled;
                    clicked => {
                        ControlPageHandler.clicked(type);
                    }
                }
            }
            TextEdit {
                vertical-stretch: 1;
                min-width: 250px;
                min-height: 170px;
                wrap: word-wrap;
                read-only: true;
                horizontal-alignment: left;
                text: log_output;
            }
        }
    }
}
